spring:
  application:
    name: zuul-edge-server
  profiles:
    active: localhost

zuul:
  routes:
    product-service:
      path: /api/1.0/product/**
      serviceId: product-service
      stripPrefix: false
    product-cache-service:
      path: /api/1.0/product-cache/**
      serviceId: product-cache-service
      stripPrefix: false

server:
  port: 8762

info:
  component: Zuul Edge Server

---
spring:
  profiles: localhost

eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka
  instance:
    instance-id: ${spring.application.name}:${random.uuid}
---

spring:
  profiles: stage

eureka:
  client:
    service-url:
      default-zone: http://eureka-server:8761/eureka
  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 10
    instance-id: ${spring.application.name}:${random.uuid}